"tests/4-print_square.txt"
_________________________
  
  4 
#### 
#### 
#### 
#### 
  10
##########
##########
##########
##########
##########
##########
##########
##########
##########
##########
  0 
# 
  1 
# 
 -1 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "4-print_square.py", line 10, in print_square
    raise ValueError("size must be >= 0")
ValueError: size must be >= 0

